name: Github CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install test dependencies
      run: pip install -r model_package/requirements-test.txt
    - name: Install package
      run: pip install -e model_package/
    - name: Run model tests
      run: pytest .
    - name: Check code style
      run: pre-commit